name: test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10', '12', '14' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: yarn --frozen-lockfile
      - run: yarn test
